import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../styles/globals.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface IRootLayout {
	children: ReactNode;
}

const RootLayout = ({ children }: Readonly<IRootLayout>) => {
	return (
		<html lang='en'>
			<body suppressHydrationWarning>{children}</body>
		</html>
	);
};

export default RootLayout;
